# Generated by Django 3.0.3 on 2020-10-31 16:48

import blogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=blogApp.models.user_directory_path),
        ),
    ]
