# Generated by Django 3.1.1 on 2020-11-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='picture',
            field=models.ImageField(upload_to='image'),
        ),
    ]
