# Generated by Django 3.1.1 on 2020-11-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20201106_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_on',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(max_length=100),
        ),
    ]
