# Generated by Django 3.1.1 on 2020-11-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20201106_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.DateField(),
        ),
    ]
