# Generated by Django 3.0.3 on 2020-11-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-last_updated'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blogs',
            new_name='blog',
        ),
    ]
